#pragma checksum "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\TagPosts.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "7d4a1421026c3611f62dcb6a2023f57d95b2dac6"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Post_TagPosts), @"mvc.1.0.view", @"/Views/Post/TagPosts.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Post/TagPosts.cshtml", typeof(AspNetCore.Views_Post_TagPosts))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\_ViewImports.cshtml"
using SpotOn;

#line default
#line hidden
#line 2 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\_ViewImports.cshtml"
using SpotOn.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"7d4a1421026c3611f62dcb6a2023f57d95b2dac6", @"/Views/Post/TagPosts.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"3ca015eeddcda1f788087fe95c64cc0a0ae9ecf2", @"/Views/_ViewImports.cshtml")]
    public class Views_Post_TagPosts : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<SpotOn.ApplicationLogic.ViewModels.Posts.PostViewModel>>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(76, 153, true);
            WriteLiteral("<style>\r\n    #postContent {\r\n        margin-left: 10%;\r\n        margin-right: 10%;\r\n        cursor: pointer;\r\n    }\r\n</style>\r\n\r\n<div id=\"postContent\">\r\n");
            EndContext();
#line 11 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\TagPosts.cshtml"
     foreach (var post in Model)
    {

#line default
#line hidden
            BeginContext(270, 12, true);
            WriteLiteral("        <div");
            EndContext();
            BeginWriteAttribute("onclick", " onclick=\"", 282, "\"", 318, 3);
            WriteAttributeValue("", 292, "getPostDetails(\'", 292, 16, true);
#line 13 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\TagPosts.cshtml"
WriteAttributeValue("", 308, post.Id, 308, 8, false);

#line default
#line hidden
            WriteAttributeValue("", 316, "\')", 316, 2, true);
            EndWriteAttribute();
            BeginContext(319, 145, true);
            WriteLiteral(" class=\"row\" style=\"border: 1px solid #dbdbdb; padding-top: 5px; padding-bottom: 5px;\">\r\n            <div class=\"col-sm-4\">\r\n                <img");
            EndContext();
            BeginWriteAttribute("src", " src=\"", 464, "\"", 486, 2);
            WriteAttributeValue("", 470, "/", 470, 1, true);
#line 15 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\TagPosts.cshtml"
WriteAttributeValue("", 471, post.ImagePath, 471, 15, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(487, 106, true);
            WriteLiteral(" height=\"150\" width=\"250\" />\r\n            </div>\r\n            <div class=\"col-sm-8\">\r\n                <h4>");
            EndContext();
            BeginContext(594, 10, false);
#line 18 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\TagPosts.cshtml"
               Write(post.Title);

#line default
#line hidden
            EndContext();
            BeginContext(604, 24, true);
            WriteLiteral(" </h4>\r\n                ");
            EndContext();
            BeginContext(629, 20, false);
#line 19 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\TagPosts.cshtml"
           Write(Html.Raw(post.Blurb));

#line default
#line hidden
            EndContext();
            BeginContext(649, 54, true);
            WriteLiteral("\r\n            </div>\r\n        </div>\r\n        <br />\r\n");
            EndContext();
#line 23 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\TagPosts.cshtml"
    }

#line default
#line hidden
            BeginContext(710, 267, true);
            WriteLiteral(@"</div>

<script>
    function getPostDetails(id) {
        $.ajax({
            url: ""/posts/"" + id,
            cache: false,
            success: function (data) {
                location.href = ""/posts/"" + id;
            }
        });
    }
</script>");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<SpotOn.ApplicationLogic.ViewModels.Posts.PostViewModel>> Html { get; private set; }
    }
}
#pragma warning restore 1591
