#pragma checksum "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6495476708e9106afb4539c18a33cafec2da8d2d"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Post_SinglePost), @"mvc.1.0.view", @"/Views/Post/SinglePost.cshtml")]
[assembly:global::Microsoft.AspNetCore.Mvc.Razor.Compilation.RazorViewAttribute(@"/Views/Post/SinglePost.cshtml", typeof(AspNetCore.Views_Post_SinglePost))]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#line 1 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\_ViewImports.cshtml"
using SpotOn;

#line default
#line hidden
#line 2 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\_ViewImports.cshtml"
using SpotOn.Models;

#line default
#line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"6495476708e9106afb4539c18a33cafec2da8d2d", @"/Views/Post/SinglePost.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"3ca015eeddcda1f788087fe95c64cc0a0ae9ecf2", @"/Views/_ViewImports.cshtml")]
    public class Views_Post_SinglePost : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<SpotOn.ApplicationLogic.ViewModels.Posts.PostViewModel>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            BeginContext(63, 469, true);
            WriteLiteral(@"
<style>
    #author {
        text-decoration: none;
        font-weight: bold;
        font-size: 20px;
        color: #65bfc9;
        margin-bottom: 5px;
    }

    #tag {
        text-decoration: none;
        font-size: 17px;
        background-color: #dbdbdb;
        padding: 0px 3px;
        color: #4f4f4f;
    }
</style>

<div class=""row"" style=""margin-top: 5%;"">
    <div class=""col-sm-3""></div>
    <div class=""col-sm-6"">
        <h1>");
            EndContext();
            BeginContext(533, 11, false);
#line 24 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
       Write(Model.Title);

#line default
#line hidden
            EndContext();
            BeginContext(544, 70, true);
            WriteLiteral(" </h1>\r\n        <div class=\"row\">\r\n            <div class=\"col-sm-6\"> ");
            EndContext();
            BeginContext(615, 10, false);
#line 26 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
                              Write(Model.Date);

#line default
#line hidden
            EndContext();
            BeginContext(625, 96, true);
            WriteLiteral(" </div>\r\n            <div class=\"col-sm-6\"> \r\n                <a id=\"author\" class=\"float-right\"");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 721, "\"", 749, 2);
            WriteAttributeValue("", 728, "user/", 728, 5, true);
#line 28 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
WriteAttributeValue("", 733, Model.Author.Id, 733, 16, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(750, 2, true);
            WriteLiteral("> ");
            EndContext();
            BeginContext(753, 21, false);
#line 28 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
                                                                            Write(Model.Author.Username);

#line default
#line hidden
            EndContext();
            BeginContext(774, 58, true);
            WriteLiteral(" </a> \r\n            </div>\r\n            \r\n        </div>\r\n");
            EndContext();
#line 32 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
         foreach(var tag in Model.Tags)
        {
            var t = tag.Substring(1);

#line default
#line hidden
            BeginContext(923, 23, true);
            WriteLiteral("            <a id=\"tag\"");
            EndContext();
            BeginWriteAttribute("href", " href=\"", 946, "\"", 959, 2);
            WriteAttributeValue("", 953, "tag/", 953, 4, true);
#line 35 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
WriteAttributeValue("", 957, t, 957, 2, false);

#line default
#line hidden
            EndWriteAttribute();
            BeginContext(960, 1, true);
            WriteLiteral(">");
            EndContext();
            BeginContext(962, 3, false);
#line 35 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
                                 Write(tag);

#line default
#line hidden
            EndContext();
            BeginContext(965, 6, true);
            WriteLiteral("</a>\r\n");
            EndContext();
#line 36 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
        }

#line default
#line hidden
            BeginContext(982, 29, true);
            WriteLiteral("\r\n        <div>\r\n            ");
            EndContext();
            BeginContext(1012, 20, false);
#line 39 "C:\Users\Thabiso Motsoko\Desktop\SpotOn\SpotOn\Views\Post\SinglePost.cshtml"
       Write(Html.Raw(Model.Body));

#line default
#line hidden
            EndContext();
            BeginContext(1032, 82, true);
            WriteLiteral("\r\n        </div>\r\n        \r\n    </div>\r\n    <div class=\"col-sm-3\"></div>\r\n</div>\r\n");
            EndContext();
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<SpotOn.ApplicationLogic.ViewModels.Posts.PostViewModel> Html { get; private set; }
    }
}
#pragma warning restore 1591
